project:
  type: website
  resources:
    - "logo/"
    - "img/"
    - "backgrounds/"

website:
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    search: true
    background: '#3e3e3e'
    left:
      - text: Home
        href: index.qmd
        icon: house-door-fill
    right:
      - text: About
        href: about/index.qmd
      - text: Research Team
        href: supervision/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Talks
        href: talks/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Blog
        href: blog/index.qmd
      - text: "CV"
        href: pdf/bahmanrostamitabarCV.pdf
        target: _blank
    tools:
      - icon: github
        href: https://github.com/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/
        target: _blank
      - icon: mortarboard-fill
        href: https://profiles.cardiff.ac.uk/staff/rostami-tabarb
        target: _blank
format:
  html:
    backgroundcolor: "#FFFFFF" # https://www.figma.com/colors/
    fontcolor: "rgb(55, 58, 60)"
    linkcolor: "#0066b2"
    mainfont: "system-ui"   # "Source Sans Pro", "-apple-system", "Segoe UI", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
    theme: [cosmo, styles.scss] # https://quarto.org/docs/output-formats/html-themes.html
    page-layout: full

