---
title: "The impact of advance demand information on the performance of production/inventory systems"
author: "Bahman Rostami-Tabar and Evren Sahin"
description: "IFAC-PapersOnLine"
year: 2015
links:
  - text: DOI
    href: https://doi.org/10.1016/j.ifacol.2015.06.338
---

<meta name="doi" content="https://doi.org/10.1080/00207543.2025.2526169">
<meta name="github" content="https://github.com/username/repo">
<meta name="code" content="https://gitlab.com/username/repo">
<meta name="arxiv" content="https://arxiv.org/abs/2301.12345">
<meta name="preprint" content="https://osf.io/preprints/socarxiv/abc123">
<meta name="data" content="https://zenodo.org/record/1234567">

## Abstract

In this paper, we evaluate the effectiveness of using Advance Demand Information (ADI) in production systems. More specifically, a supplier-customer relationship from the supplier's perspective is studied where we integrate the value of Advance Demand Information provided by the customer. Hence, ADI is in the form of customer firm orders that are transmitted to the supplier in advance of customer's future demand requirements. In this paper, we study a production system, with a single product, finite capacity and constant production times where the policy used is a base stock based on ADI. Additionally, it is assumed that ADI is perfect which means that the quantity and the due date of the order transmitted by the customer to the supplier is deterministic and do not change over time. We perform a discrete-time simulation model to evaluate the impact of using ADI on the considered production system. Moreover, we conduct a sensitivity analysis to examine the effect of capacity and demand variability on the production system. We observe that a base-stock policy in conjunction with ADI may increase the supplier efficiency by reducing the total cost of inventory and backorder costs. The rate of total cost reduction is a function of demand variability and production capacity.