---
title: "Non-stationary demand forecasting by cross-sectional aggregation"
author: "Bahman Rostami-Tabar, Mohamed Zied Babai, Yves Ducq, and Aris Syntetos"
description: "International Journal of Production Economics"
year: 2015
links:
  - text: DOI
    href: https://doi.org/10.1016/j.ijpe.2015.10.001
---

<meta name="doi" content="https://doi.org/10.1080/00207543.2025.2526169">
<meta name="github" content="https://github.com/username/repo">
<meta name="code" content="https://gitlab.com/username/repo">
<meta name="arxiv" content="https://arxiv.org/abs/2301.12345">
<meta name="preprint" content="https://osf.io/preprints/socarxiv/abc123">
<meta name="data" content="https://zenodo.org/record/1234567">

## Abstract

In this paper the relative effectiveness of top-down (TD) versus bottom-up (BU) approaches is compared for cross-sectionally forecasting aggregate and sub-aggregate demand. We assume that the sub-aggregate demand follows a non-stationary Integrated Moving Average (IMA) process of order one and a Single Exponential Smoothing (SES) procedure is used to extrapolate future requirements. Such demand processes are often encountered in practice and SES is one of the standard estimators used in industry (in addition to being the optimal estimator for an IMA process). Theoretical variances of forecast error are derived for the BU and TD approach in order to contrast the relevant forecasting performances. The theoretical analysis is supported by an extensive numerical investigation at both the aggregate and sub-aggregate level, in addition to empirically validating our findings on a real dataset from a European superstore. The results demonstrate the increased benefit resulting from cross-sectional forecasting in a non-stationary environment than in a stationary one. Valuable insights are offered to demand planners and the paper closes with an agenda for further research in this area.