---
title: "Forecasting for lead-time period by temporal aggregation: Whether to combine and how"
author: "Bahman Rostami-Tabar, Thanos E. Goltsos, and Shixuan Wang"
description: "Computers in Industry"
year: 2023
links:
  - text: DOI
    href: https://doi.org/10.1016/j.compind.2022.103803
---

<meta name="doi" content="https://doi.org/10.1080/00207543.2025.2526169">
<meta name="github" content="https://github.com/username/repo">
<meta name="code" content="https://gitlab.com/username/repo">
<meta name="arxiv" content="https://arxiv.org/abs/2301.12345">
<meta name="preprint" content="https://osf.io/preprints/socarxiv/abc123">
<meta name="data" content="https://zenodo.org/record/1234567">

## Abstract

Temporal aggregation (TA) refers to transforming a time series from higher to lower frequencies (e.g. monthly to quarterly). There are two different types of aggregation: overlapping and non-overlapping; which, when added to the option of using original time series, present the forecaster with three approaches to produce required forecasts over the lead-time period: (i) non-overlapping aggregation (NOA) (ii) overlapping aggregation (OA); and (iii) bottom-up to aggregate forecast (BU). Forecasters may then need to decide which approach to use or alternatively combine the forecasts generated by the three approaches, instead. In this study, we design and execute an experiment using the M4 competition dataset, to explore the effect of different initial frequencies (i.e. daily, monthly, and quarterly), data aggregation levels and combination methods on forecast accuracy. We are surprised to find that neither temporal aggregation strategies have an overall gain on forecasting accuracy. Equally concerning is the fact that straight (average) combinations of these forecasts are similarly of no benefit to the accuracy. To extract the benefits of both well-supported individual forecasting practices of temporal aggregation and combination, we propose a framework that aims to combine temporal aggregation and forecasting combinations using a polynomially weighted average with multiple learning rates. We find considerable overall improvement in forecasting accuracy by using the proposed combination, especially for longer lead-times. We discuss areas where the framework is expected to perform best in the future and conclude that further research is required in this area. We note that our method can work in parallel of others and close with an agenda for further research on forecasting by temporal aggregation.